[package]
name = "wpilib"
version = "0.0.1"
authors = ["Kyle Stachowicz <kylestach99@gmail.com>"]
build = "build.rs"

[dependencies]
atom="*"

[lib]
name = "wpilib"
path = "src/lib.rs"

[[bin]]
name = "test"
path = "src/main.rs"
